apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: house-price-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-username/istio-lab-repo.git'
    targetRevision: HEAD
    path: helm/house_price
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
